### ISSUE TITLE
GAMS return codes

### ISSUE THREAD

**Issue by andreaslundell** [coin-or/SHOT#15]
Is there some way to get a meaningful text out of the GAMS error return codes using the C++ API? For example, when I give an integer variable a noninteger bound it seems to return code 768. But I cannot find the meaning of this code anywhere...

**Comment by svigerske** [comment]
Where do you use the C++ API and which function you call that gives you this return code?

**Comment by andreaslundell** [comment]
I run the following (stupid) model:

```
Variables  i1,i2,i3,objvar;
Integer Variables  i1,i2,i3;
Equations  e1,e2,e3;

e1..  i1+i2+i3 - objvar =E= 0;
e2.. -i1*i2 =L= 0;
e3.. -i1*i3 =L= 0;

i1.lo = 0.1; i1.up = 2;
i2.lo = 0; i2.up = 6;
i3.lo = 2; i3.up = 3;

Model m / all /;

$if not set MINLP $set MINLP MINLP
Solve m using %MINLP% minimizing objvar;
```

with `./SHOT model.gms`

Then, when running the line:

https://github.com/coin-or/SHOT/blob/a6bc11fca1e7f1b1baff267892f9a0499fe6463c/src/ModelingSystem/ModelingSystemGAMS.cpp#L313

It will give a return code 768. If I change the lower bound to an integer it works. I can live with the fact that it doesn't work, but I would just like to have a more informative error message... Running the model from inside GAMS would give the message:
`**** Matrix error - bounds on discrete variables have to be integer`

Is it possible to get this message somehow?

**Comment by svigerske** [comment]
The GAMS call in here just returns '3', which means execution error (https://www.gams.com/latest/docs/UG_GAMSReturnCodes.html#UG_GAMSReturnCodes_ListOfErrorCodes). However, `system()` does not return this 3 exactly, but encodes this in some way. From the system()-manpage: `       In the last two cases, the return value is a "wait status" that can be examined using the macros described in waitpid(2).  (i.e., WIFEXITED(), WEXITSTATUS(), and so on).`

768 is actually 3*256, so I guess that `WEXITSTATUS(768)` would give you `768>>8`.

The GAMS call stores the listing file in `loadgms.tmp/listing`. Parsing this file for all lines starting with `****` could be useful.
Since this is assigned to me, probably you would actually like me to do this :).

**Comment by andreaslundell** [comment]
I was hoping for a magic getStatusMessage()-function, but parsing the file is the next best thing I guess... If you have nothing better to do a Sunday afternoon, then feel free, but otherwise, I can manage it myself later :D

**Comment by svigerske** [comment]
I had better things to do :), but I'll give it a try now.
