### ISSUE TITLE
Redirect GAMS output

### ISSUE THREAD

**Issue by andreaslundell** [coin-or/SHOT#55]
Is there some simple way of redirecting also the GAMS output to spdlog when running SHOT directly but using e.g. CONOPT as NLP solver?

**Comment by svigerske** [comment]
I started looking into this and there seems to be a way to do that, at least for some situations.

It's a bit tricky if running through GAMS, because if I register another print callback in gev (`modelingEnvironment`) I create an infinite loop when the callback sends to the spdlog, which then sends to gev, which then sends to the callback again. :) That is, the NLP solver uses the same gev object as the one where the GAMS output is send to.

**Comment by andreaslundell** [comment]
Yes, I had the same thought as well. This isn't really a high priority, it is just the perfectionist in me wanting to have the same output layout as with Ipopt :)
